// Generated by CoffeeScript 1.6.2
(function() {
  var JSON2CSV;

  JSON2CSV = function(objArray, quote) {
    var array, head, i, index, line, str, value;

    array = (typeof objArray !== "object" ? JSON.parse(objArray) : objArray);
    str = "";
    line = "";
    head = array[0];
    if (quote) {
      for (index in array[0]) {
        value = index + "";
        line += "\"" + value.replace(/"/g, "\"\"") + "\",";
      }
    } else {
      for (index in array[0]) {
        line += index + ",";
      }
    }
    line = line.slice(0, -1);
    str += line + "\r\n";
    i = 0;
    while (i < array.length) {
      line = "";
      if (quote) {
        for (index in array[i]) {
          value = array[i][index] + "";
          line += "\"" + value.replace(/"/g, "\"\"") + "\",";
        }
      } else {
        for (index in array[i]) {
          line += array[i][index] + ",";
        }
      }
      line = line.slice(0, -1);
      str += line + "\r\n";
      i++;
    }
    return str;
  };

  exports.json2csv = JSON2CSV;

}).call(this);
